### ISSUE TITLE
Doesn't work on Runbo X6

### ISSUE THREAD

**Issue by zdila** [NeiroNx/Intercomm#2]
Hello

I've compiled and installed latest version from git but phone doesn't communicate. I've set COM Port to /dev/ttyMT3.

Module: not detected

Any other information I can provide?

**Comment by NeiroNx** [comment]
may be your device does not have **busybox** with **stty** and **ioctl** aplets, used to configure COM port

**Comment by zdila** [comment]
I have busybox but not sure about those applets. I'll check it and will report here. Thanks.

**Comment by NeiroNx** [comment]
and which **Build dev: ** version you have. may be it not detected properetly.

**Comment by zdila** [comment]
It is 0.7d, yesterday cloned from github, compiled and installed.

**Comment by NeiroNx** [comment]
program detect phone by part of *Build.DEVICE* string,  if it not found in samples - it use default settings and may have problems with override defaults. https://github.com/NeiroNx/Intercomm/blob/master/app/src/main/java/com/nxn/intercomm/uartIntercom.java#L337

And i am commited now some major changes...

**Comment by zdila** [comment]
I'll check it in the evening. Thanks.

**Comment by zdila** [comment]
With current HEAD it works. Thanks.
